### ISSUE TITLE
Improve Observers

### ISSUE THREAD

**Issue by jaumef** [gisce/crm_poweremail#25]
The current observers field is a comma-separated string:

![image](https://user-images.githubusercontent.com/19925414/36263402-72464ed8-126a-11e8-9c89-d8a9a9c24286.png)

It would be better to use a Many2Many with `res_partner_address`

Also would be great to have a BCC Observers as "secret observers"

**Comment by ecarreras** [comment]
To don't break the behavior, maybe we can convert the new field to the *comma separated list*

**Comment by jaumef** [comment]
## TODO

Replace the Watchers field with a new page with "many2many" fields alongisde with their _comma separated list_ related field. We need both lists:

- Watchers (CC)
- Secret watchers (BCC)

The many2many fields are related to a `res.partner.address`.
Then we may do an `on_change` method for those "many2many" to add the related addresses to the string field without duplicated addresses and respecting the addresses that are added manually.
