### ISSUE TITLE
Add a way to subscribe

### ISSUE THREAD

**Issue by ecarreras** [gisce/crm_poweremail#28]
Maybe #25 is a way to subrive to a concrete case, but maybe some user want to subscribe to a section.

Then all the cases of this section must add him as a observer.

**Comment by jaumef** [comment]
@ecarreras Sure!, adding a "section observers" that automatically adds those would be great!

Should we add them to the observers field when a new case is created? Or use this new field when adding CC/BCC addresses of the case sendmails?

**Comment by jaumef** [comment]
Section subscribing can be done from CORE CRM
Case subscribing was done in this module

Missing a merge for the address getting methods (https://github.com/gisce/erp/pull/6828)
