### ISSUE TITLE
Add related documents to CRM.Case

### ISSUE THREAD

**Issue by jaumef** [gisce/crm_poweremail#36]
The attachments on the case-related mailboxes are stored in the mailbox object so the crm_case user can't see them.

ADD a new tab with the related documents to the case.

**Comment by ecarreras** [comment]
This field could be a field function which merges the stored attachments in `crm.case` object and all the attachments from linked mails for that case

**Comment by jaumef** [comment]
Yup, that was the Idea :+1:

**Comment by jaumef** [comment]
We commented this issue on the #24
